name: Update LeetCode stats

on:
  schedule:
    - cron: "0 3 * * *"   # каждый день в 03:00 UTC
  workflow_dispatch:      # кнопка «Run workflow» вручную

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python update_readme.py
      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: update LeetCode stats" && git push)
